### ISSUE TITLE
Error NOTFOUND 28842:80

### ISSUE THREAD

**Issue by jorgitoh** [nuncdev/raid-scanner#1]
Hi, I have this error:

23:54:05 - info: Scanning gym at -34.61773, -58.361738
{ Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 29842 29842:80
    at ClientRequest.onError (C:\Raid\node_modules\tunnel-agent\index.js:177:17)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:400:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

Btw, how can i put the proxy info, ip:port?.

**Comment by jorgitoh** [comment]
Solved:

Proxy format:
http://ip:port
